name = "QuadraticRationals"
uuid = "24a7753b-e0fe-47b8-adb9-9a0ca98f67d3"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.1.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
julia = "1"
Primes = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
